services:
  front:
    image: node:lts-slim
    working_dir: /app
    tty: true

  firebase:
    build:
      context: .
      dockerfile: ./firebase/Dockerfile
    volumes:
      - ./.firebaserc:/opt/firebase/.firebaserc
      - ./firebase.json:/opt/firebase/firebase.json
      - ./firestore.indexes.json:/opt/firebase/firestore.indexes.json
      - ./firestore.rules:/opt/firebase/firestore.rules
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
      - ./extensions:/opt/firebase/extensions
    ports:
      - 9099:9099 # Firebase Authentication
      - 8080:8080 # Cloud Firestore
      - 9199:9199 # Cloud Storage
      - 4000:4000 # Emulator Suite UI
    working_dir: /opt/firebase
    command: firebase emulators:start